sudo: false

language: php

php:
  - 7.0

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install

script:

matrix:
  fast_finish: true

jobs:
  include:
    - stage: lint
      php: 7.1
      install:
        - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
        - composer require --dev "phpstan/phpstan" "friendsofphp/php-cs-fixer:^2.8"
        - touch .phpstan.neon
      script:
        # Static analyzer check
        - ./vendor/bin/phpstan analyze -c .phpstan.neon --level=4 --no-progress src
        # Check the code style
        - IFS=$'\n'; COMMIT_SCA_FILES=($(git diff --name-only --diff-filter=ACMRTUXB "${TRAVIS_COMMIT_RANGE}")); unset IFS
        - ./vendor/bin/php-cs-fixer fix --config=.php_cs.php -v --dry-run --diff --stop-on-violation --using-cache=no --path-mode=intersection -- "${COMMIT_SCA_FILES[@]}"
